#################################################################################################
# High burden, high impact 
# simAdjustments_mortality_MiP_IPTp_IPTi.R
# Monique Ambrose
# February 2020
#
# 
# Adjust simulation output to account for IPTi, MiP, and IPTp effects. Also calculate mortality.
#
#
# DESCRIPTION:
# From DTK simulation output on the number of new infections in the 15-30 and 30-50 age groups
#    and the IPTp coverage rates estimated for each DS from DHS data, calculate information 
#    relevant to malaria in pregnancy:
#     - how does IPTp coverage affect PfPR in relevant age groups?
#     - how many additional severe cases occur due to maternal severe anemia?
#     - how many mLBW and mLBW deaths occur?
#     - how many malaria-attributable stillbirths occur?
# Use the results of these calculations to modify the simulation output files for number of 
#    severe cases, PfPR, mLBW, and stillbirths.
# Finally, calculate mortality rates for children U5 and across all ages using the number of 
#    severe cases, non-severe cases, and number of mLBWs.
#
#
# REQUIREMENTS:
# - Requires a csv file in the base simulation folder called 'scenario_adjustment_info.csv' with a row for each scenario and columns:
#     1) ScenarioName - name of each scenario name (folder name for that simulation output)
#     2) IPTp_string - indicates which IPTp coverage should be applied
#     3) future_projection - indicates whether scenario is a simulation of the past or a future projection
#     4) IPTi - indicates whether or not IPTi should be applied in this scenario
# - Requires that IPTp coverage and dose distribution have already been calculated and saved in 
#    appropriate format (this can be done using malaria-bf-hbhi/parameter_estimates/find_iptp_coverage.R and 
#    malaria-bf-hbhi/parameter_estimates/get_iptp_doses_from_dhs.R). Required files are:
#     - hbhi_{country_name}/IPTp/estimated_2010_2020_num_doses.csv
#     - hbhi_{country_name}/IPTp/estimated_2010_2020_IPTp_each_DS.csv
#     - hbhi_{country_name}/IPTp/projected_trajectory_2020_2025_IPTp_each_DS.csv  <- only needed if scenario_adjustment_info.csv has IPTp_string=trajectory
#     - hbhi_{country_name}/IPTp/estimated_ci_l_2010_2020_IPTp_each_DS.csv  <- only needed if scenario_adjustment_info.csv has IPTp_string=estimateWorseCoverage
#     - hbhi_{country_name}/IPTp/estimated_ci_u_2010_2020_IPTp_each_DS.csv  <- only needed if scenario_adjustment_info.csv has IPTp_string=estimateBetterCoverage
# - Requires a csv with parameters relevant to birth/death/pregnancy rates, MiP, IPTp, and mortality in hbhi_{country_name}/simulation_inputs/parameters_mortality_MiP_IPTp_IPTi.csv
# - Requires IPTi_adjustment.csv and  IPTi_adjustment.Uall.csv to be in the simulation output folder if scenario_adjustement_info.csv has IPTi=TRUE
#    (these can be generated using  hbhi-nigeria/simulation/IPTi_scaling/0_master.R) 
# - Requires the HBHI simulation output files for each of the scenarios to have been generated by the HBHI analyzers and saved in the appropriate simulation scenario folders
#
#
#################################################################################################

library(data.table)
library(tidyverse)
library(lubridate)

### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
#                     set filepaths, read in data, load needed functions
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###

##### User-specified information on scenarios to use: ############################################################################################### 
user = Sys.getenv("USERNAME")
user_path = file.path("C:/Users",user)

# set name of country to run
country_name = 'Nigeria'
if(country_name =='Burkina'){
  box_hbhi_filepath = paste(user_path, '/Box/hbhi_burkina', sep='')
  # filepath for simulation output
  sim_output_filepath = paste(box_hbhi_filepath, '/simulation_output/2010_to_2020/_v16', sep='')
  # sim_output_filepath = paste(box_hbhi_filepath, '/simulation_output/2020_to_2025/BF NSP projection v5', sep='')
  sim_output_base_filepath_2010_allInter = paste(box_hbhi_filepath, '/simulation_output/2010_to_2020/_v16/BF 2010_2020 allInterventions', sep='')
  simname_stem = 'BF NSP projection '
} else if (country_name=='Nigeria'){
  box_hbhi_filepath = paste(user_path, '/Box/NU-malaria-team/projects/hbhi_nigeria', sep='')
  # filepath for simulation output
  sim_output_filepath = paste(box_hbhi_filepath, '/simulation_output/2020_to_2030_v3', sep='')
  # sim_output_filepath = paste(box_hbhi_filepath, '/simulation_output/2020_to_2030_v1', sep='')
  # sim_output_filepath = paste(box_hbhi_filepath, '/simulation_output/2020_to_2030_test2', sep='')
  sim_output_base_filepath_2010_allInter = paste(box_hbhi_filepath, '/simulation_output/2010_to_2020_v10/NGA 2010-20 burnin_hs+itn+smc', sep='')
} else{
  warning('Country name not supported')
}

# set timespan of simulations
first_year = 2020  # 2010, 2020
last_year = 2030 # 2019, 2025, 2021

# filepath for scripts
script_base_filepath = paste(user_path, '/Documents/hbhi-nigeria/simulation/IPTp_mortality_postprocessing', sep='')
####################################################################################################################################################


# load needed functions
source(paste0(script_base_filepath, '/malariaInPregnancy_functions.R'))
source(paste0(script_base_filepath, '/malariaMortality_functions.R'))
source(paste0(script_base_filepath, '/IPTi_functions.R'))
source(paste0(script_base_filepath, '/get_MiP_protection_coverage.R'))

# population sizes and CHW coverages (for Burkina)
if(country_name =='Burkina'){
  # DS proposed for increased CHW communication
  projection_CHW_communication_filename = paste(box_hbhi_filepath,'/scenarios/BFA_delivery_activities.csv', sep='')
  # populations sizes for each DS
  ds_pop_size_filepath = paste(box_hbhi_filepath, '/burkina_DS_pop.csv', sep='')
}else if(country_name =='Nigeria'){
  # populations sizes for each DS
  ds_pop_size_filepath = paste(box_hbhi_filepath, '/nigeria_LGA_pop.csv', sep='')
}
# read in population sizes for each DS
ds_pop_size = read.csv(ds_pop_size_filepath)

# filename for estimated IPTp coverage
iptp_estimates_filename = paste(box_hbhi_filepath,'/IPTp/estimated_2010_2020_IPTp_each_DS.csv', sep='')
iptp_estimates_ci_l_filename = paste(box_hbhi_filepath,'/IPTp/estimated_ci_l_2010_2020_IPTp_each_DS.csv', sep='')
iptp_estimates_ci_u_filename = paste(box_hbhi_filepath,'/IPTp/estimated_ci_u_2010_2020_IPTp_each_DS.csv', sep='')
iptp_project_trajectory_filename = paste(box_hbhi_filepath,'/IPTp/projected_trajectory_2020_2030_IPTp_each_DS.csv', sep='')

# filename for estimated number of IPTp doses taken by IPTp recipients in each year
iptp_dose_number_filename = paste(box_hbhi_filepath,'/IPTp/estimated_2010_2020_num_doses.csv', sep='')
# read in estimated IPTp coverage
iptp_coverage_df = read.csv(iptp_estimates_filename, as.is=TRUE)[,-1]
ds_names = iptp_coverage_df$DS
# read in the number of IPTp doses taken by people who receive IPTp
iptp_dose_number = read.csv(iptp_dose_number_filename, row.names=1)

# IPTi adjustment files
ipti_adj_Uall_filename = paste(sim_output_filepath, '/IPTi_adjustment.Uall.csv', sep='')
ipti_adj_U5_filename = paste(sim_output_filepath, '/IPTi_adjustment.csv', sep='')
# if those files don't exist, see whether the CI version does. if so, convert to preferred format
ipti_adj_Uall_CI_filename = paste(sim_output_filepath, '/IPTi_adjustment_Uall_withCI.csv', sep='')
ipti_adj_U5_CI_filename = paste(sim_output_filepath, '/IPTi_adjustment_U5_withCI.csv', sep='')
if(!file.exists(ipti_adj_Uall_filename)){
  if(file.exists(ipti_adj_Uall_CI_filename)){
    convert_CI_to_mean_format(filename_CI=ipti_adj_Uall_CI_filename, filename_mean=ipti_adj_Uall_filename)
  }
}
if(!file.exists(ipti_adj_U5_filename)){
  if(file.exists(ipti_adj_U5_CI_filename)){
    convert_CI_to_mean_format(filename_CI=ipti_adj_U5_CI_filename, filename_mean=ipti_adj_U5_filename)
  }
}


# filename for parameters describing birth and death rates, pregnancy information, IPTp protection, CFRs
parameter_filepath = paste0(box_hbhi_filepath, '/simulation_inputs/parameters_mortality_MiP_IPTp_IPTi.csv')
parameter_df_0 = read.csv(parameter_filepath, as.is=TRUE)
parameter_df = parameter_df_0[,c('parameter_name', country_name)]  # subset to current country
colnames(parameter_df)[colnames(parameter_df)==country_name] = 'parameter_value'  # change column name from country name to 'parameter_value'


# get filenames and information for all of the scenarios currently being processed
scenario_adjusmtnet_info_filepath = paste(sim_output_filepath,  '/scenario_adjustment_info.csv', sep='')
if(file.exists(scenario_adjusmtnet_info_filepath)){
  scenario_adjustment_info = read.csv(scenario_adjusmtnet_info_filepath, as.is=TRUE)
  # check whether scenario name column already exists. if not, create it
  if(!('ScenarioName' %in% colnames(scenario_adjustment_info))){
    scenario_adjustment_info$ScenarioName = paste(simname_stem, scenario_adjustment_info$Scenario_no)
  }
} else{
  warning('csv file containing information about set of simulations not found')
}

# set whether an output csv file should be saved with the metrics for each DS and each run
save_output_csv_each_ds = FALSE


### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
#                                     get parameter values
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
# parameters describing protection against stillbirth and mLBW from IPTp
#    relative risk of the adverse outcome given 0, 1, 2, or >=3 IPTp doses, relative to 0 doses (see the mortality notes for explanations of parameters)
iptp_relative_risk_estimate = c(parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_0dose'],
                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_1dose'],
                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_2dose'],
                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_3dose'])
iptp_relative_risk_estimateBetterProtection = c(parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_0dose_better'],
                                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_1dose_better'],
                                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_2dose_better'],
                                                parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_3dose_better'])
iptp_relative_risk_estimateWorseProtection = c(parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_0dose_worse'],
                                               parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_1dose_worse'],
                                               parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_2dose_worse'],
                                               parameter_df$parameter_value[parameter_df$parameter_name == 'iptp_relative_risk_estimate_3dose_worse'])

# probability of malaria-attributable LBW or stillbirth given that the mother was infected with malaria and had taken 0 IPTp doses
pm_LBW_iptp0 = parameter_df$parameter_value[parameter_df$parameter_name == 'pm_LBW_iptp0']
pm_still_iptp0 = parameter_df$parameter_value[parameter_df$parameter_name == 'pm_still_iptp0']

# parameters describing birth rate, non-malarial stillbirth, and fraction of first or second births
births_per_person_per_month = parameter_df$parameter_value[parameter_df$parameter_name == 'births_per_person_per_month']
d0 = parameter_df$parameter_value[parameter_df$parameter_name == 'd0']  # probability of death for a non-LBW infant
d1 = parameter_df$parameter_value[parameter_df$parameter_name == 'd1']  # probability of death for a LBW infant
non_mal_stillbirth_fraction = parameter_df$parameter_value[parameter_df$parameter_name == 'non_mal_stillbirth_fraction']  # fraction of births that result in stillbirth from causes other than malaria
births_per_person_per_month_live = births_per_person_per_month * (1-non_mal_stillbirth_fraction)  # the number of births per month per individual, excluding stillbirths from non-malarial causes
frac_first_second_birth = parameter_df$parameter_value[parameter_df$parameter_name == 'frac_first_second_birth']  # fraction of all births that are first or second births (based off rough calculations with various assumptions about age of mother at first birth and years between births (see malaria_low_birth_rate_estimates.R))
frac_preg_under_30 = parameter_df$parameter_value[parameter_df$parameter_name == 'frac_preg_under_30']  # fraction of births that occur to individuals under 30, based off rough calculations with various assumptions about age of mother at first birth and years between births (see malaria_low_birth_rate_estimates.R)

# parameters describing probability of severe maternal anemia due to malaria
prob_severe_from_MiP = parameter_df$parameter_value[parameter_df$parameter_name == 'prob_severe_from_MiP']  # probability of maternal severe anemia attributable to malaria
reduced_prob_severe_IPTp = parameter_df$parameter_value[parameter_df$parameter_name == 'reduced_prob_severe_IPTp']  # reduced probability of maternal severe anemia attributable to malaria if >=1 dose of IPTp is used
weeks_protection_each_dose = parameter_df$parameter_value[parameter_df$parameter_name == 'weeks_protection_each_dose']  # weeks IPTp is assumed to prevent new infections
prob_severe_MiP_treated = parameter_df$parameter_value[parameter_df$parameter_name == 'prob_severe_MiP_treated']  # probability a woman with severe disease from MiP receives treatment

# indirect mortality parameters (describe probability a clinical case of malaria will eventually lead to an incident of indirect mortality)
#   in Ross et al, these are cases that occur after the malaria episode. Here, they could represent deaths during or after a malaria that would
#   not have been classified as deaths due to severe malaria but that also wouldn't have occurred if that individual hadn't been infected with malaria
# parameters and model from Ross et al. 2006
# ISSUE WITH INDIRECT MORTALITY: since it is calculated using teh number of new cases, when treatment increases, number of new cases can increase (as calculated by model), leading to INCREASE instead of DECREASE in indirect mortality. set to zero unti lthis issue is resolved. 
starting_prob_1 = parameter_df$parameter_value[parameter_df$parameter_name == 'starting_prob_1']  # 0.037  # (QD from Ross et al, upper value)
starting_prob_2 = parameter_df$parameter_value[parameter_df$parameter_name == 'starting_prob_2']  # 0.01  # (QD from Ross et al, lower value)
age_shape_param = parameter_df$parameter_value[parameter_df$parameter_name == 'age_shape_param']  # (aF* from Ross et al)

# mortality parameters
cfr_severe_treated = parameter_df$parameter_value[parameter_df$parameter_name == 'cfr_severe_treated']
cfr_severe_untreated_1 = parameter_df$parameter_value[parameter_df$parameter_name == 'cfr_severe_untreated_1']
cfr_severe_untreated_2 = parameter_df$parameter_value[parameter_df$parameter_name == 'cfr_severe_untreated_2']



### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
#                   iterate through scenarios, calculating adjustments
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###

for(i_scen in 1:length(scenario_adjustment_info$ScenarioName)){

  ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
  #               read in scenario information and simulation output files
  ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
  
  # get filename and coverage information for this scenario
  scenarioName_cur = scenario_adjustment_info$ScenarioName[i_scen]
  scenarioName_IPTi = scenario_adjustment_info$IPTi_scenario_name[i_scen]
  sim_output_base_filepath = paste(sim_output_filepath, '/', scenarioName_cur, sep='')
  future_projection_flag = scenario_adjustment_info$future_projection_flag[i_scen]
  coverage_string = scenario_adjustment_info$IPTp_string[i_scen]

  # filename for simulation output on number of new infections in each month by age group
  sim_output_filename = paste(sim_output_base_filepath, "/newInfections_PfPR_cases_monthly_byAgeGroup.csv", sep='')
  # filename for simulation output on all age monthly cases and PfPR (will be adjusted with MiP outcomes and used for plotting)
  sim_output_allAgeMonthly_filename_cur = paste(sim_output_base_filepath, "/All_Age_Monthly_Cases.csv", sep='')
  # filename for simulation output on all U5 severe cases and PfPR (will be adjusted with MiP outcomes and used for plotting)
  sim_output_U5PfPR_filename_cur = paste(sim_output_base_filepath, "/U5_PfPR_ClinicalIncidence_severeTreatment.csv", sep='')
  
  # check whether output for this scenario exists
  if(file.exists(sim_output_filename)){
    print(paste('Starting scenario: ', scenarioName_cur, ' (', i_scen, ' out of ', length(scenario_adjustment_info$ScenarioName),')', sep=''))
    # read in the simulation results using data.table
    sim_output_all_runs = fread(sim_output_filename)
    
    # subset simoutput to appropriate years
    sim_output_all_runs = sim_output_all_runs %>% filter(year <= last_year) %>% filter(year >= first_year)

    # replace the column name LGA with DS_Name, as is expected later in the script
    if('LGA' %in% colnames(sim_output_all_runs)){
      colnames(sim_output_all_runs)[which(colnames(sim_output_all_runs) == 'LGA')] = 'DS_Name'
    }
    if('Pop' %in% colnames(sim_output_all_runs)){
      colnames(sim_output_all_runs)[which(colnames(sim_output_all_runs) == 'Pop')] = 'Statistical Population'
    }
    
    # if output folder does not already exist, create it
    if (!dir.exists(paste(sim_output_base_filepath, '/mortality_LBW', sep=''))){
      dir.create(paste(sim_output_base_filepath, '/mortality_LBW', sep=''))
      print('creating new output directory')
    }

    
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    #                    set IPTp coverage and doses through time for this scenario
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    
    IPTp_coverages = get_IPTp_coverages(iptp_estimates_filename=iptp_estimates_filename, iptp_dose_number_filename=iptp_dose_number_filename, 
                                        future_projection_flag=future_projection_flag, 
                                        first_year=first_year, last_year=last_year, coverage_string=coverage_string,
                                        iptp_estimates_ci_l_filename=iptp_estimates_ci_l_filename, iptp_estimates_ci_u_filename=iptp_estimates_ci_u_filename,
                                        iptp_project_trajectory_filename=iptp_project_trajectory_filename)
    iptp_coverage_df = IPTp_coverages[[1]]
    iptp_dose_number = IPTp_coverages[[2]]
    ds_names = IPTp_coverages[[3]]
    
    # set the parameters describing protection from IPTp on mLBW (and stillbirths)
    if(coverage_string == 'estimateWorseCoverage'){
      iptp_relative_risk = iptp_relative_risk_estimateWorseProtection
    } else if(coverage_string == 'estimateBetterCoverage'){
      iptp_relative_risk = iptp_relative_risk_estimateBetterProtection
    } else{
      iptp_relative_risk = iptp_relative_risk_estimate
    }  
    
    # among people who receive IPTp in a given year, what fraction gets each number of doses
    frac_iptp_years = first_year:last_year
    # read in from saved file (based on DHS/MIS data)
    frac_iptp_1 = as.numeric(iptp_dose_number[1,])
    frac_iptp_2 = as.numeric(iptp_dose_number[2,])
    frac_iptp_3 = as.numeric(iptp_dose_number[3,])
    
    
    # set parameters describing protection provided by IPTp
    # malaria-attributable low birth weight (mLBW)
    pm_LBW_iptp = pm_LBW_iptp0 * iptp_relative_risk   # probability of a mLBW infant given that the mother was infected with malaria in her first or second pregnancy - values for 0, 1, 2, >=3 IPTp doses
    # malaria-attributable stillbirth
    # use three versions of the relative risk values to calculate protection against stillbirth because we don't have much data here
    pm_still_iptp_v1 = pm_still_iptp0 * iptp_relative_risk * 0.5
    pm_still_iptp_v2 = pm_still_iptp0 * iptp_relative_risk * 1
    pm_still_iptp_v3 = pm_still_iptp0 * iptp_relative_risk * 2
    pm_still_iptp_v1[1] = pm_still_iptp0  # set the 0-dose risk back to the original value
    pm_still_iptp_v2[1] = pm_still_iptp0
    pm_still_iptp_v3[1] = pm_still_iptp0
    list_of_pm_still_iptp = list( pm_still_iptp_v2)  # list(pm_still_iptp_v1, pm_still_iptp_v2, pm_still_iptp_v3)
    names_for_pm_still_iptp = c('still100')  # c('still50', 'still100', 'still200')
    i_still = 1  # which index to use for generating final plotting info
    
    
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    #               call functions to calculate MiP-related outcomes and adjust sim output
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    print('... adjusting for MiP and IPTp')
    
    
    # adjust simulation output files for MiP and IPTp impacts
    pm_still_iptp=list_of_pm_still_iptp[[i_still]]
    name_for_pm_still_iptp=names_for_pm_still_iptp[i_still]
    # filenames for after adjustment
    sim_output_allAgeMonthly_filename_MiP = gsub( '.csv', paste('_withMiP', coverage_string, '_', name_for_pm_still_iptp,'.csv', sep=''), sim_output_allAgeMonthly_filename_cur)
    sim_output_allAgeMonthly_filename_IPTi = gsub( '.csv', paste('_withIPTi.csv', sep=''), sim_output_allAgeMonthly_filename_MiP)
    sim_output_U5PfPR_filename_IPTi = gsub( '.csv', paste('_withIPTi.csv', sep=''), sim_output_U5PfPR_filename_cur)
    # sim_output_MiP_mortality_filename = paste(sim_output_base_filepath, '/malariaBurden_withAdjustments_', coverage_string, '_', name_for_pm_still_iptp,'.csv', sep='')
    sim_output_MiP_mortality_filename= paste(sim_output_base_filepath, '/malariaBurden_withAdjustments.csv', sep='')

    # calculate MiP related counts and probabilities for each run in simulation output
    # saves data tables on population sizes in various age groups, probability of avoiding infection in each month,
    # probability of being infected during pregnancy, and number of pregnancies, m-stillbirths, mLBW, and mLBW-deaths
    calculate_pregnancy_values_across_runs(sim_output_all_runs=sim_output_all_runs, first_year=first_year, last_year=last_year, ds_names=ds_names,
                                           iptp_coverage_df=iptp_coverage_df, pm_LBW_iptp=pm_LBW_iptp, list_of_pm_still_iptp=list_of_pm_still_iptp,
                                           names_for_pm_still_iptp=names_for_pm_still_iptp, d0=d0, d1=d1, non_mal_stillbirth_fraction=non_mal_stillbirth_fraction,
                                           births_per_person_per_month=births_per_person_per_month, frac_first_second_birth=frac_first_second_birth,
                                           frac_preg_under_30=frac_preg_under_30, frac_iptp_1=frac_iptp_1, frac_iptp_2=frac_iptp_2, frac_iptp_3=frac_iptp_3,
                                           frac_iptp_years=frac_iptp_years, coverage_string=coverage_string,
                                           sim_output_base_filepath=sim_output_base_filepath, sim_output_base_filepath_2010_allInter=sim_output_base_filepath_2010_allInter,
                                           future_projection_flag=future_projection_flag, overwrite_files_flag=FALSE)

    adjust_sim_output_for_MiP(prob_severe_from_MiP=prob_severe_from_MiP,
                              reduced_prob_severe_IPTp=reduced_prob_severe_IPTp,
                              prob_severe_MiP_treated=prob_severe_MiP_treated,
                              weeks_protection_each_dose=weeks_protection_each_dose,
                              frac_iptp_1=frac_iptp_1,
                              frac_iptp_2=frac_iptp_2,
                              frac_iptp_3=frac_iptp_3,
                              iptp_coverage_df=iptp_coverage_df,
                              pm_still_iptp=pm_still_iptp,
                              name_for_pm_still_iptp=name_for_pm_still_iptp,
                              coverage_string=coverage_string,
                              sim_output_base_filepath=sim_output_base_filepath,
                              sim_output_allAgeMonthly_filename_cur=sim_output_allAgeMonthly_filename_cur,
                              sim_output_allAgeMonthly_filename_MiP=sim_output_allAgeMonthly_filename_MiP)

    
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    #               call functions to adjust sim output for IPTi
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    
    # add IPTi adjustments using scaling values from Manuela
    if(scenario_adjustment_info$IPTi[i_scen]){
      print('... adjusting for IPTi')
      adjust_sim_output_for_ITPi(ipti_adj_U5_filename=ipti_adj_U5_filename,
                                 ipti_adj_Uall_filename=ipti_adj_Uall_filename,
                                 scenarioName_IPTi=scenarioName_IPTi,
                                 sim_output_allAgeMonthly_filename_cur=sim_output_allAgeMonthly_filename_MiP,
                                 sim_output_allAgeMonthly_filename_IPTi=sim_output_allAgeMonthly_filename_IPTi,
                                 sim_output_U5PfPR_filename_cur=sim_output_U5PfPR_filename_cur,
                                 sim_output_U5PfPR_filename_IPTi=sim_output_U5PfPR_filename_IPTi,
                                 pfpr_all_colname = 'PfPR_MiP_adjusted',
                                 pfpr_U5_colname = 'PfPR.U5',
                                 cases_all_colname = 'New.Clinical.Cases',
                                 cases_U5_colname = 'Cases.U5',
                                 severe_all_colname = 'New.Severe.Cases',
                                 severe_U5_colname = 'Severe.cases.U5')
      
      sim_output_allAgeMonthly_filename_old=sim_output_allAgeMonthly_filename_IPTi
      sim_output_U5PfPR_filename_old=sim_output_U5PfPR_filename_IPTi
    } else{
      sim_output_allAgeMonthly_filename_old=sim_output_allAgeMonthly_filename_MiP
      sim_output_U5PfPR_filename_old=sim_output_U5PfPR_filename_cur
    }
# <<<<<<< HEAD
    
# =======
    # specify column names in the allAgeMonthly and U5PfPR data frames
# >>>>>>> 427293e1305184e546d48ac6bbd7f040b4d4049c
    cases_all_colname = 'New.Clinical.Cases'
    cases_U5_colname = 'Cases.U5'
    severe_all_colname = 'New.Severe.Cases'
    severe_maternal_colname = 'severe_maternal'
    severe_U5_colname = 'Severe.cases.U5'
    severe_treated_all_colname = 'severe_total_treated'
    severe_treated_U5_colname = 'Num_U5_Received_Severe_Treatment'
    pop_size_U5_colname = 'Pop.U5'
    
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    #               call functions to adjust sim output for mortality
    ### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ###
    
    # add mortality adjustments
    print('... adjusting for mortality')
    adjust_sim_output_mortality(cfr_severe_treated=cfr_severe_treated, # case fatality rate for severe, treated cases
                                cfr_severe_untreated_1=cfr_severe_untreated_1, # case fatality rate for severe, treated cases (upper estimate)
                                cfr_severe_untreated_2=cfr_severe_untreated_2, # case fatality rate for severe, treated cases (lower estimate)
                                starting_prob_1=starting_prob_1,  # (QD from Ross et al, upper value)
                                starting_prob_2=starting_prob_2,  # (QD from Ross et al, lower value)
                                age_shape_param=age_shape_param,  # (aF* from Ross et al)
                                sim_output_allAgeMonthly_filename_old=sim_output_allAgeMonthly_filename_old,
                                sim_output_U5PfPR_filename_old=sim_output_U5PfPR_filename_old,
                                sim_output_MiP_mortality_filename=sim_output_MiP_mortality_filename,
                                cases_all_colname=cases_all_colname,
                                cases_U5_colname=cases_U5_colname,
                                severe_all_colname=severe_all_colname,
                                severe_maternal_colname=severe_maternal_colname,
                                severe_U5_colname=severe_U5_colname,
                                severe_treated_all_colname=severe_treated_all_colname,
                                severe_treated_U5_colname=severe_treated_U5_colname,
                                pop_size_U5_colname = pop_size_U5_colname)
    
    
  } else warning(paste(' scenario not found:', sim_output_filename))
}


