### ==========================================================================================
### HBHI modelling - Nigeria: IPTi effectiveness estimation and scaling of simulation outputs
### Feb 2020, MR
### Updated April 2020, added CIs
### Plotting functions
### ====================================================================================


f_generatePlotDat <- function(dataset, years = 2020) {
  #' Generates PfPR, incidence and mortality 
  #' (relative difference between IPTi scaled and not scaled outcomes in percentage for positives, cases and deaths)
  #' for U1 and U5 (hardcoded) 
  #' Transforms dataset into long format 
  #' @param dataset  dataset with predictions in wide format
  #' @param years filter by specified year
  #' 
  dataset <- dataset %>% mutate(
    PfPR.U1_diff = (1 - PfPR.U1_scl / PfPR.U1) * 100,
    PfPR.U5_diff = (1 - PfPR.U5_scl / PfPR.U5) * 100,
    incidence.U1_diff = (1 - incidence.U1_scl / incidence.U1) * 100,
    incidence.U5_diff = (1 - incidence.U5_scl / incidence.U5) * 100,
    mortality.U1_diff = (1 - mortality.U1_scl / mortality.U1) * 100,
    mortality.U5_diff = (1 - mortality.U5_scl / mortality.U5) * 100
  )

  outcomevar <- colnames(dataset)[grep(".U", colnames(dataset))]

  dataset <- dataset %>%
    filter(year %in% years) %>%
    pivot_longer(cols = outcomevar) %>%
    separate(name, into = c("outcome", "Uage"), sep = ".U") %>%
    separate(Uage, into = c("Uage", "scl"), sep = "_")

  dataset$outcome_fct <- factor(dataset$outcome,
    levels = c("PfPR", "incidence", "mortality"),
    labels = c("PfPR\n", "incidence\n", "mortality\n")
  )
  dataset$Uage_f <- paste0("age U ", dataset$Uage)

  return(dataset)
}


f_plot1 <- function(plotdat) {
  #' Generates a barchart showing unadjusted outcomes in grey and adjusted outcomes in color 
  #' Barchart is per scenario on the x axis and age + outcome as facets
  #' (relative difference between IPTi scaled and not scaled outcomes in percentage for positives, cases and deaths)
  #' @param plotdat  dataset in format as generated by f_generatePlotDat
  #' 
  if ("measure" %in% colnames(plotdat)) {
    errorDat <- plotdat %>%
      filter(measure != "mean" & Uage %in% c("1", "5") & scl == "scl") %>%
      dplyr::select(year, scenarioNr, Scencov, value, measure, outcome, Uage_f, scl) %>%
      pivot_wider(names_from = measure, values_from = value)

    plotdat <- subset(plotdat, measure == "mean")
  }


  tempplot <- ggplot(data = subset(plotdat, Uage %in% c("1", "5"))) + theme_cowplot() +
    geom_bar(data = subset(plotdat, Uage %in% c("1", "5") & is.na(scl)), 
             aes(x = scenarioNr, y = value), stat = "identity", fill = "lightgrey") +
    geom_bar(data = subset(plotdat, Uage %in% c("1", "5") & scl == "scl"), 
             aes(x = scenarioNr, y = value, fill = scenarioNr), stat = "identity") +
    scale_fill_manual(values = scencols) +
    scale_y_continuous(expand = c(0, 0)) +
    customTheme + 
    theme(legend.position = "none") +
    labs(y = "predicted outcome value", x = "Scenario")+
    facet_wrap(Uage_f ~ outcome, scales = "free", nrow = 2) 

  if ("measure" %in% colnames(plotdat)) {
    tempplot <- tempplot +
      geom_errorbar(data = errorDat, aes(x = scenarioNr, ymin = low_ci, ymax = up_ci), stat = "identity", width = 0.3) +
      labs(caption = "\nErrorbars show confidence intervals around protective efficacies (based on Esu et al 2019")
  }

  return(tempplot)
}



p_PlotFacet <- function(dat = tbl_U15.sclAggrNat, outcomeVar = "PfPR", ageU = "U1", facetVar = NULL, s_year = 2025, SAVE = F, relRed = F) {
  #' Generates a barchart showing unadjusted outcomes in grey and adjusted outcomes in color 
  #' Barchart is per scenario on the x axis and age + outcome as facets
  #' (relative difference between IPTi scaled and not scaled outcomes in percentage for positives, cases and deaths)
  #' @param dat  aggregated dataset, i.e. tbl_U15.sclAggrNat
  #' @param outcomeVar  specify outcome variable
  #' @param ageU  subet by age U1 or U5, or Uall
  #' @param facetVar  select variable that should be shown in facets
  #' @param s_year  filter by year
  #' @param SAVE  boolean, if TRUE, saved plot in outdir
  #' @param relRed  boolean, if TRUE; show relative reduction
  #' 
  #' # outcomeVar <- paste0(outcomeVar, ".", ageU)
  if (outcomeVar %in% c("Cases", "pos", "Severe.cases", "Anaemia", "deaths")) outcomeVar <- paste0(outcomeVar, ".", ageU, ".pop")
  if (outcomeVar %in% c("incidence", "incidence2", "PfPR", "mortality")) outcomeVar <- paste0(outcomeVar, ".", ageU)
  if (!(outcomeVar %in% colnames(dat))) stop("Variable not defined")

  dat <- as.data.frame(dat)
  dat <- subset(dat, (Run_Number == 0 | Run_Number == "aggregated mean") & year == s_year)
  nLGA <- length(unique(subset(tbl_U15.scl)$LGA))


  dat$outcomevar <- dat[, colnames(dat) == outcomeVar]
  dat$outcomevar_scl <- dat[, colnames(dat) == paste0(outcomeVar, "_scl")]

  if ("measure" %in% colnames(dat)) {
    errorDat <- dat %>%
      filter(measure != "mean") %>%
      dplyr::select(year, scenarioNr, Scencov, outcomevar_scl, outcomevar, facetVar, measure) %>%
      pivot_wider(names_from = measure, values_from = c(outcomevar_scl, outcomevar))

    dat <- subset(dat, measure == "mean")
  }

  pout <- ggplot(data = dat) +
    theme_cowplot() +
    geom_bar(aes(x = scenarioNr, y = outcomevar, group = Scencov), stat = "identity", fill = "grey", position = "dodge", show.legend = FALSE) +
    geom_bar(aes(x = scenarioNr, y = outcomevar_scl, fill = scenarioNr), stat = "identity", position = "dodge", show.legend = FALSE) +
    scale_fill_manual(values = scencols) +
    scale_color_manual(values = scencols) +
    scale_y_continuous(labels = scales::comma) +
    labs(
      alpha = "Intervention\ncoverage (%)",
      x = "Scenario", y = outcomeVar,
      title = paste0("Estimated IPTi effectiveness for ", outcomeVar),
      subtitle = "Coloured=with IPTi, Grey= without IPTi",
      caption = paste0("Predicted for the year ", s_year, " for ", nLGA, " eligible LGAs, grouped by archetype")
    ) +
    coord_flip() +
    theme(legend.position = "right")

  if ("measure" %in% colnames(dat)) {
    pout <- pout +
      geom_errorbar(data = errorDat, aes(x = scenarioNr, ymin = outcomevar_scl_low_ci, ymax = outcomevar_scl_up_ci, group = Scencov), stat = "identity", position = pos, width = 0.3) +
      labs(caption = "\nErrorbars show confidence intervals around protective efficacies (based on Esu et al 2019")
  }

  if (relRed) {
    dat$reduction <- 1 - (dat$outcomevar_scl / dat$outcomevar)


    pout <- ggplot(data = dat) +
      theme_cowplot() +
      #   geom_bar(aes(x = reorder(scenarioname, outcomevar), y = outcomevar), stat = "identity", fill = "lightgrey") +
      #   geom_bar(aes(x = reorder(scenarioname, outcomevar), y = outcomevar_scl), fill = "deepskyblue3",  stat = "identity") +
      geom_bar(aes(x = reorder(scenarioname, reduction), y = reduction), fill = "deepskyblue3", stat = "identity") +
      labs(
        x = "Scenario, CM coverage", y = "Relative reduction",
        title = paste0("Estimated IPTi effectiveness for ", outcomeVar),
        subtitle = paste0("Predicted for the year ", s_year, " for ", nLGA, " eligible LGAs, grouped by archetype")
      ) +
      coord_flip()
  }

  if (!is.null(facetVar)) {
    dat$facetVar <- dat[, colnames(dat) == facetVar]
    pout <- pout + facet_wrap(~ dat$facetVar, scales = "free") +
      theme(
        strip.text.x = element_text(face = "bold"),
        strip.text.y = element_text(face = "bold"),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = 0.5)
      )
  }

  # pout <- pout + customTheme_noAngle
  if (SAVE) {
    ggsave(paste0(outcomeVar, facetVar, "_", s_year, "_test.png"),
      plot = pout, path = file.path(outdir),
      width = 16, height = 12, dpi = 200, device = "png"
    )
  }

  return(pout)
}



f_genMap <- function(data, fillVar, facetVar, SAVE = T) {
  #' Generate map 
  #' @param data  data
  #' @param fillVar  variable to show 
  #' @param facetVar  select variable that should be shown in facets
  #' @param SAVE  boolean, if TRUE, saved plot in outdir
  #' 
  data$fillVar <- data[, colnames(data) == fillVar]
  data$facetVar <- data[, colnames(data) == facetVar]
  AggrStatus <- as.character(unique(data$facetVar))

  filename <- paste0(fillVar, "_IPTi_CM", "_by ", AggrStatus, ".png")


  mapout <- ggplot(data = subset(data, !is.na(scenario))) + theme_map() +
    geom_polygon(data = subset(data, LGA %in% IPTiareas & !is.na(scenario)), aes(x = long, y = lat, group = group), fill = "grey", color = "black", size = 0.35) +
    geom_polygon(data = subset(data, IPTyn.f == 1 & !is.na(scenario)), aes(x = long, y = lat, group = group, fill = fillVar), color = "black", size = 0.35) +
    facet_wrap(~scenarioNr, ncol = 2) + customTheme +
    # scale_fill_manual(values = c(rev(orangered), greens, lila)) +
    scale_fill_continuous(type = "viridis") +
    guides(fill = guide_colourbar(barwidth = 3, barheight = 15)) +
    theme(
      strip.text.x = element_text(size = 22, face = "bold"),
      strip.text.y = element_text(size = 22, face = "bold"),
      strip.background = element_blank(),
      legend.position = c(0.7, 0.15),
      legend.title = element_text(size = 20, face = "bold"),
      legend.text = element_text(size = 20, face = "bold")
    ) +
    labs(title = "", fill = fillVar)

  if (SAVE & length(unique(data$facetVar)) > 1) ggsave(filename, plot = mapout, path = file.path(outdir), width = 20, height = 18, dpi = DPI, device = "png")
  if (SAVE & length(unique(data$facetVar)) == 1) ggsave(filename, plot = mapout, path = file.path(outdir), width = 16, height = 12, dpi = DPI, device = "png")
  # if(SAVE)warning(paste0("Plot saved to ",outdir))
  return(mapout)
}



f_map <- function(varName, perYear = T, SAVE = T) {
  #' Generate map 
  #' @param varName  data
  #' @param perYear  variable to show 
  #' @param SAVE  boolean, if TRUE, saved plot in outdir
  #' 
  mapdat.df$varName <- mapdat.df[, varName]

  pplot <- ggplot(data = subset(mapdat.df, LGA %in% IPTiareas)) + theme_map() +
    geom_polygon(aes(x = long, y = lat, group = group), fill = "grey", color = "black", size = 0.35) +
    geom_polygon(aes(x = long, y = lat, group = group, fill = varName), color = "black", size = 0.35) +
    # scale_fill_manual(values = c(rev(orangered[1:2]), greens)) +
    customTheme +
    scale_fill_viridis(option = "viridis", labels = comma) +
    guides(fill = guide_colourbar(barwidth = 3, barheight = 15)) +
    theme(
      strip.text.x = element_text(size = 22, face = "bold"),
      strip.text.y = element_text(size = 22, face = "bold"),
      strip.background = element_blank(),
      legend.position = c(0.7, 0.15),
      legend.title = element_text(size = 18, face = "bold"),
      legend.text = element_text(size = 15, face = "bold")
    ) +
    theme(legend.position = "right") +
    labs(title = varName, fill = "Total events averted\nper year (2020-2025)")

  if (SAVE) ggsave(paste0(varName, ".png"), plot = pplot, path = file.path(outdir), width = 18, height = 10, dpi = DPI, device = "png")
  return(pplot)
}
